config/routes.rb
Hotseats::Application.routes.draw do
  
  resources :payment_notifications

  post 'payment_notifications', to: "payment_notifications#create", as: "pn"

  devise_for :applicants

  devise_for :employers
  get '/post-a-job', to: "jobs#new"
  get '/welcome', to: "info#welcome", as: "welcome"
  get '/apply-to-job/:id', to: "job_applications#create", as: "apply" 
  get 'view-job/:id', to: "jobs#show", as: "viewjob"
  get 'view-applications/:id', to: "jobs#applications", as: "viewapplications"
  get 'my-jobs', to: "jobs#myjobs", as: "myjobs"
  get 'approve-applicants', to: "admins#approve", as: "approveid"
  put 'approve-applicants/:id', to: "admins#update", as: "ap"
  get 'employer', to: "info#employer"
  get 'guarantee', to: "info#guarantee"
  get 'jobpayment', to: "jobs#payment"
  get 'prepaid/:id', to: "jobs#prepaid", as: "prepaid"

  mount Monologue::Engine, at: '/blog' 

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  resource :jobs
  
  root to: "info#home"
end

app/models/employer.rb
class Employer < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :city, :company_name, :website, :logo, :prepaid, :admin

  mount_uploader :logo, LogoUploader
  
  has_many :jobs
  
  validates :name, presence: true
  validates :city, presence: true
  validates :company_name, presence: true
  
  
  def job_applications
    JobApplication.where(:job_id=>jobs)
  end
  
end

app/views/employers/shared/_employer_header.haml
#sessionsheader
  #sessions_header_content.container_24
    #flash
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    #logo
      = link_to image_tag("logo.png", :alt => "HotSeats.co Logo"), root_path
    #social
      - if current_employer
        Employers:
        \#{link_to "My Jobs", myjobs_path}
        \#{link_to "Logout", destroy_employer_session_path, :method=>:delete}
      - else
      - unless current_employer
        - if current_applicant
          = link_to "Logout", destroy_applicant_session_path, :method=>:delete
        - else
          Job Seekers:
          \#{link_to "Login", new_applicant_session_path}
          \#{link_to "Signup", new_applicant_registration_path}
      = link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com'
      = link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com'
      = link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/'
    .clear
    #logintitle.grid_18.push_3
      %h2 Employers Sign In

app/views/employers/shared/_employer_header.html.erb
 <div id="sessionsheader">
	<div id="sessions_header_content" class="container_24">
			<div id= "flash">
				<%- flash.each do |name, msg| -%>
				    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
				<%- end -%>  
			</div> 		
			<div id="logo">
				<%= link_to image_tag("logo.png", :alt => "HotSeats.co Logo"), root_path %>
			</div>
			
			<div id="social">
				<%- if current_employer %>
		
				Employers:
				<%= link_to "My Jobs", myjobs_path %>
				<%= link_to "Logout", destroy_employer_session_path, :method=>:delete %>
			<%- else %>
				
			<%- end%>
			
			<%- unless current_employer %>
				<%- if current_applicant %>
				
					<%= link_to "Logout", destroy_applicant_session_path, :method=>:delete %>
				<%- else %>
				Job Seekers:
					<%= link_to "Login", new_applicant_session_path  %>
					<%= link_to "Signup", new_applicant_registration_path  %>
			
				<%- end%>
				
			<%-end%>

			<%= link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com' %>
			<%= link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com' %>
			<%= link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/' %>
				
			</div>
				<div class="clear"></div>
				
			<div id ="logintitle" class = "grid_18 push_3">
				<h2>Employers Sign In</h2>
			</div>
	</div>			
</div>

app/views/employers/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/employers/shared/_resend_employer_header.haml
#sessionsheader
  #sessions_header_content.container_24
    #flash
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    #logo
      = image_tag("logo.png", :alt => "HotSeats.co Logo")
    #social
      - if current_employer
      - #= image_tag current_employer.logo.url
        Employers:
        \#{link_to "My Jobs", myjobs_path}
        \#{link_to "Logout", destroy_employer_session_path, :method=>:delete}
      - else
      - unless current_employer
        - if current_applicant
          = link_to "Logout", destroy_applicant_session_path, :method=>:delete
        - else
          Job Seekers:
          \#{link_to "Login", new_applicant_session_path}
          \#{link_to "Signup", new_applicant_registration_path}
      = link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com'
      = link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com'
      = link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/'
    .clear
    #logintitle.grid_18.push_3
      %h2 Resend confirmation instructions

app/views/employers/shared/_resend_employer_header.html.erb
 <div id="sessionsheader">
	<div id="sessions_header_content" class="container_24">
			<div id= "flash">
				<%- flash.each do |name, msg| -%>
				    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
				<%- end -%>  
			</div> 		
			<div id="logo">
				<%= image_tag("logo.png", :alt => "HotSeats.co Logo") %>
			</div>
			
			<div id="social">
				<%- if current_employer %>
				<%-#= image_tag current_employer.logo.url %>
				Employers:
				<%= link_to "My Jobs", myjobs_path %>
				<%= link_to "Logout", destroy_employer_session_path, :method=>:delete %>
			<%- else %>
				
			<%- end%>
			


			<%- unless current_employer %>
				<%- if current_applicant %>
				
					<%= link_to "Logout", destroy_applicant_session_path, :method=>:delete %>
				<%- else %>
				Job Seekers:
					<%= link_to "Login", new_applicant_session_path  %>
					<%= link_to "Signup", new_applicant_registration_path  %>
			
				<%- end%>
				
			<%-end%>

			<%= link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com' %>
			<%= link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com' %>
			<%= link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/' %>
				
			</div>
				<div class="clear"></div>
				
			<div id ="logintitle" class = "grid_18 push_3">
				<h2>Resend confirmation instructions</h2>
			</div>
		
	</div>		

	
</div>

app/views/employers/shared/_reset_employer_header.haml
#sessionsheader
  #sessions_header_content.container_24
    #flash
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    #logo
      = image_tag("logo.png", :alt => "HotSeats.co Logo")
    #social
      - if current_employer
      - #= image_tag current_employer.logo.url
        Employers:
        \#{link_to "My Jobs", myjobs_path}
        \#{link_to "Logout", destroy_employer_session_path, :method=>:delete}
      - else
      - unless current_employer
        - if current_applicant
          = link_to "Logout", destroy_applicant_session_path, :method=>:delete
        - else
          Job Seekers:
          \#{link_to "Login", new_applicant_session_path}
          \#{link_to "Signup", new_applicant_registration_path}
      = link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com'
      = link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com'
      = link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/'
    .clear
    #logintitle.grid_18.push_3
      %h2 Forgot Your Password?

app/views/employers/shared/_reset_employer_header.html.erb
 <div id="sessionsheader">
	<div id="sessions_header_content" class="container_24">
			<div id= "flash">
				<%- flash.each do |name, msg| -%>
				    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
				<%- end -%>  
			</div> 		
			<div id="logo">
				<%= image_tag("logo.png", :alt => "HotSeats.co Logo") %>
			</div>
			
			<div id="social">
				<%- if current_employer %>
				<%-#= image_tag current_employer.logo.url %>
				Employers:
				<%= link_to "My Jobs", myjobs_path %>
				<%= link_to "Logout", destroy_employer_session_path, :method=>:delete %>
			<%- else %>
				
			<%- end%>
			


			<%- unless current_employer %>
				<%- if current_applicant %>
				
					<%= link_to "Logout", destroy_applicant_session_path, :method=>:delete %>
				<%- else %>
				Job Seekers:
					<%= link_to "Login", new_applicant_session_path  %>
					<%= link_to "Signup", new_applicant_registration_path  %>
			
				<%- end%>
				
			<%-end%>

			<%= link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com' %>
			<%= link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com' %>
			<%= link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/' %>
				
			</div>
				<div class="clear"></div>
				
			<div id ="logintitle" class = "grid_18 push_3">
				<h2>Forgot Your Password?</h2>
			</div>
		
	</div>		

	
</div>