config/routes.rb
Hotseats::Application.routes.draw do
  
  resources :payment_notifications

  post 'payment_notifications', to: "payment_notifications#create", as: "pn"

  devise_for :applicants

  devise_for :employers
  get '/post-a-job', to: "jobs#new"
  get '/welcome', to: "info#welcome", as: "welcome"
  get '/apply-to-job/:id', to: "job_applications#create", as: "apply" 
  get 'view-job/:id', to: "jobs#show", as: "viewjob"
  get 'view-applications/:id', to: "jobs#applications", as: "viewapplications"
  get 'my-jobs', to: "jobs#myjobs", as: "myjobs"
  get 'approve-applicants', to: "admins#approve", as: "approveid"
  put 'approve-applicants/:id', to: "admins#update", as: "ap"
  get 'employer', to: "info#employer"
  get 'guarantee', to: "info#guarantee"
  get 'jobpayment', to: "jobs#payment"
  get 'prepaid/:id', to: "jobs#prepaid", as: "prepaid"

  mount Monologue::Engine, at: '/blog' 

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  resource :jobs
  
  root to: "info#home"
end

app/models/job.rb
class Job < ActiveRecord::Base
  
  attr_accessible :title, :location, :description, :info, :employer, :position_type, :employer_attributes, :jobpaid  
  belongs_to :employer
  has_many :job_applications
  has_one :payment_notification
  accepts_nested_attributes_for :employer
  
  validates :employer, presence: true
  validates :title, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :info, presence: true
  validates_inclusion_of :position_type, in: %w(Full-Time Contract Freelance)
  
  scope :full_time, where(:position_type=>"Full-Time")
  scope :contract, where(:position_type=>"Contract")
  scope :freelance, where(:position_type=>"Freelance")
  
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :employer_signed_in, only: [:myjobs]
  before_filter :correct_employer?, only: [:applications, :prepaid] 

  def new
    @job = Job.new
    @job.build_employer unless current_employer

    if current_employer
      if current_employer.prepaid = nil
        current_employer.update_attributes(:prepaid => 0)
        else
      end 
    end     

  end

  def create
    
    @job = Job.new params[:job]
    @job.employer = @employer = current_employer || @job.employer

    

    if @job.valid? && @employer.valid?
      @job.save!
      
      if current_employer
        render :payment
       
      else
        
        render :payment
      end    
    else
      render action: :new
    end
  end

  def show

      @job = Job.find(params[:id])

  end 

  def myjobs
    
    @employerjobs = current_employer.jobs
 
  end  

  def applications

    @job = Job.find(params[:id]) 

    job_id = @job.id

    @applications = JobApplication.all(:select => "job_applications.*, applicants.*", :joins => :applicant, :conditions => "job_id = #{job_id}")

  end

  def prepaid
    current_balance = current_employer.prepaid
    @job = Job.find(params[:id])
    if current_balance > 0
       @job.update_attributes(:jobpaid => true)
       current_employer.update_attributes(:prepaid => current_balance - 1)
       @message = "Your Job has been successfully purchased with prepaid credits and created"

    else
       @message = "Error - You have no prepaid job credits"
    end 


  end

  private

  def employer_signed_in
      if is_employer? == true
        return true
      else

      redirect_to root_path
    end
  end 

  def correct_employer?

    
       @job = Job.find(params[:id])

       if current_employer.id == @job.employer_id

          return true

        else

        redirect_to root_path

      end
  end      
    
end

app/helpers/jobs_helper.rb
module JobsHelper

	def is_employer?
  		if current_employer.present?
  				return true
  			else
  				return false
  		end
  		
  	end

end

app/views/jobs/applications.haml
= render "layouts/header"
#wrapper.container_24
  #pagetitle
    %h2
      = @job.title
      applicants:
  - @applications.each do |app|
    #applicantbox
      %p
      %h6 Applicant name:
      %p
        = app.name
      %p
      %h6 Email:
      %p
        = app.email
      %p
      %p
      %h6 Location:
      %p
        = app.city
      %p
      %h6 Website:
      %p
        = app.website
      %p
      %h6 Resume:
      = link_to "Curriculum Vitae Download", "#{app.resume}"
      %p
      %h6 Applied date
      %p
        = app.created_at
  = render "layouts/footer"

app/views/jobs/applications.html.erb
<%= render "layouts/header" %>
<div id="wrapper" class="container_24">
<div id= "pagetitle">	
	<h2><%= @job.title %> applicants:</h2>
</div>

<% @applications.each do |app| %>
<div id="applicantbox">
	<p>
	<h6>Applicant name:</h6>
	<p>
	 <%= app.name %>
	 <p> 
	 <h6>Email:</h6>
	 <p>
	 
	<%= app.email %>
	 <p> 

	 <p> 
	 <h6>Location:</h6>
	 <p>
	 <%= app.city %>
	 <p>
	 <h6>Website:</h6>
	 <p>
	 <%= app.website %>
	 <p>
	 <h6>Resume:</h6>

	 <%= link_to "Curriculum Vitae Download", "#{app.resume}" %>
	 <p> 
	<h6>Applied date</h6>
	 <p> 
	 <%= app.created_at %>

</div>	
 

 <% end %>

 <%= render "layouts/footer" %>

app/views/jobs/created.haml
%h1

app/views/jobs/myjobs.haml
= render "layouts/header"
#wrapper.container_24
  - if is_employer? == true
    #pagetitle
      %h2 Your Job Posts
    - @employerjobs.each do |job|
      #joblistingbox
        %h4
          = link_to job.title, viewjob_path(job)
        %p
          = job.location
        %p
        %h6= link_to "View applications", viewapplications_path(job)
        %p
  - else
    you are not an employer
  = render "layouts/footer"

app/views/jobs/myjobs.html.erb
<%= render "layouts/header" %>
<div id="wrapper" class="container_24">

	<% if is_employer? == true %> 
<div id= "pagetitle">	
	<h2> Your Job Posts </h2>
</div>
	<% @employerjobs.each do |job| %>
	<div id="joblistingbox">
		<h4> <%= link_to job.title, viewjob_path(job) %> </h4>
		 <p> 
		 <%= job.location %>
		 <p>
		 <h6><%= link_to "View applications", viewapplications_path(job) %></h6>
		 <p>
	</div>	 	
		<% end %> 	
			<% else %>

			you are not an employer

			<% end %>	

<%= render "layouts/footer" %>

app/views/jobs/new.haml
= render "layouts/header"
#wrapper.container_24
  #jobcontainer.grid_17

    .title
      %h1 Post Your Job
    .solidline.grid_16
      .subheader
        %h4
          %r Step 1: 
          Job Option
      #joboption
        #joboptionheader
          #singlejob
            Single Job
          #jobpackage
            5 Job Package 
          .clearfix
        #pricesingle
          £109
        #price5
          £99 
        .clearfix  
        #perjob
          per job
        #perjobleft
          per job 
        .clearfix  
        #total
          Total price £496
        #input
          %input{:name => "1job", :type => "checkbox", :value => "1job"} Select
        #inputleft
          %input{:name => "1job", :type => "checkbox", :value => "1job"} Select  
 
      .subheader
        %h4
          %r Step 2:
          Job Details
          #jobdetails
            #jobdetailsheader
              #jobdetailstext
                Job Details
            =semantic_form_for @job do |f|


              =f.inputs do

                =f.input :title ,:label => "Job Title"
                =f.input :location
                =f.input :position_type, as: :select, collection: ["Full-Time", "Contract", "Freelance"]
                =f.input :description ,:label => "Job Description"
                =f.input :info ,:label => "How to Apply"
    
                -unless current_employer 
                  .subheader
                  %h4
                    %r Step 3:
                    Company Information
                    #companyinfoheader
                      #jobdetailstext
                        Company Information
                  =f.semantic_fields_for :employer do |e| 
                    =e.input :email
                    =e.input :password
                    =e.input :password_confirmation
                    =e.input :name
                    =e.input :city
                    =e.input :company_name
                    =e.input :website
                    =e.input :logo, as: :file
                    
                #jobcreatebutton      
                  =f.action :submit, :as => :button     
  #sidebar.grid_7
    .sidebarheader
      %h3 100% Satisfaction Guarantee
    .sidebarline
  .sidebar_content.grid_7
    %p
      Post your job on HotSeats.co and if you're
      not completely satisfied with the results
      you receive simply contact us for a full
      and courteous refund
    .sidebarheader
      %h3 "My CV was one of the best CVs the company had ever seen."
      .sidebarline
  
  .redlink.grid_7
    %p
    Receive a full report on your CV's strengths and weaknesses #{link_to 'CLICK HERE', "http://www.careerconsultants.co.uk/find-me-a-job/cv-assessment/" }  
  .sidebar_content.grid_7
    %h3 Post a Job
    .sidebarline
    .sidebar_content
      %p Post a job with HotSeats.co today for guaranteed recruitment satisfaction.
    .redbutton_sidebar
      .buttontext= link_to 'Post Job', new_jobs_path
  .clear   

  = render "layouts/footer"   
      
      

app/views/jobs/payment.haml
= render "layouts/header"
#wrapper.container_24
  #jobcontainer.grid_24
    #make_payment_title
      %h3
        Make Payment for #{@job.title} Job listing
    #one_job_payment
      %h4
        1 Job Listing
      .paypalbutton
        %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
          %input{:name => "cmd", :type => "hidden", :value => "_xclick"}/
          %input{:name => "business", :type => "hidden", :value => "FF6Q6HD44S4R6"}/
          %input{:name => "lc", :type => "hidden", :value => "GB"}/
          %input{:name => "item_name", :type => "hidden", :value => "HotSeats Job Listing"}/
          %input{:name => "item_number", :type => "hidden", :value => @job.id}/
          %input{:name => "amount", :type => "hidden", :value => "109.00"}/
          %input{:name => "currency_code", :type => "hidden", :value => "GBP"}/
          %input{:name => "button_subtype", :type => "hidden", :value => "services"}/
          %input{:name => "no_note", :type => "hidden", :value => "1"}/
          %input{:name => "no_shipping", :type => "hidden", :value => "1"}/
          %input{:name => "custom", :type => "hidden", :value => "1job"}/
          %input{:name => "notify_url", :type => "hidden", :value => pn_url}/
          %input{:name => "bn", :type => "hidden", :value => "PP-BuyNowBF:btn_buynow_LG.gif:NonHosted"}/
          %input{:alt => "PayPal – The safer, easier way to pay online.", :border => "0", :name => "submit", :src => "https://www.paypal.com/en_GB/i/btn/btn_buynow_LG.gif", :type => "image"}/
          %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypal.com/en_GB/i/scr/pixel.gif", :width => "1"}/
    /
      "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
    #five_job_payment
      %h3 5 Job Listings
      .paypalbutton2
        %form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
          %input{:name => "cmd", :type => "hidden", :value => "_xclick"}/
          %input{:name => "business", :type => "hidden", :value => "FF6Q6HD44S4R6"}/
          %input{:name => "lc", :type => "hidden", :value => "GB"}/
          %input{:name => "item_name", :type => "hidden", :value => "Five HotSeats Job Listings"}/
          %input{:name => "item_number", :type => "hidden", :value => @job.id}/
          %input{:name => "amount", :type => "hidden", :value => "496.00"}/
          %input{:name => "currency_code", :type => "hidden", :value => "GBP"}/
          %input{:name => "button_subtype", :type => "hidden", :value => "services"}/
          %input{:name => "no_note", :type => "hidden", :value => "1"}/
          %input{:name => "no_shipping", :type => "hidden", :value => "1"}/
          %input{:name => "custom", :type => "hidden", :value => "5job"}/
          %input{:name => "notify_url", :type => "hidden", :value => pn_url}/
          %input{:name => "bn", :type => "hidden", :value => "PP-BuyNowBF:btn_buynow_LG.gif:NonHosted"}/
          %input{:alt => "PayPal – The safer, easier way to pay online.", :border => "0", :name => "submit", :src => "https://www.paypal.com/en_GB/i/btn/btn_buynow_LG.gif", :type => "image"}/
          %img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypal.com/en_GB/i/scr/pixel.gif", :width => "1"}/
    - if current_employer
      #prepaid
        %h5
          Your prepaid Job Balance is:
          \#{current_employer.prepaid}
          - if current_employer.prepaid > 0
            = link_to 'Pay with prepaid Balance', prepaid_path(@job.id)
= render "layouts/footer"

app/views/jobs/payment.html.erb
<%= render "layouts/header" %>
<div id="wrapper" class="container_24">
	<div id="jobcontainer" class= "grid_24">
		<div id="make_payment_title"><h3>Make Payment for <%= @job.title %> Job listing</h3></div>
		<div id="one_job_payment">
			<h4>1 Job Listing</h3>
			<div class="paypalbutton">	
				<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
				<input type="hidden" name="cmd" value="_xclick">
				<input type="hidden" name="business" value="FF6Q6HD44S4R6">
				<input type="hidden" name="lc" value="GB">
				<input type="hidden" name="item_name" value="HotSeats Job Listing">
				<input type="hidden" name="item_number" value= "<%= @job.id %>">
				<input type="hidden" name="amount" value="109.00">
				<input type="hidden" name="currency_code" value="GBP">
				<input type="hidden" name="button_subtype" value="services">
				<input type="hidden" name="no_note" value="1">
				<input type="hidden" name="no_shipping" value="1">
				<input type="hidden" name="custom" value="1job">
				<input type="hidden" name="notify_url" value="<%= pn_url %>">
				<input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynow_LG.gif:NonHosted">
				<input type="image" src="https://www.paypal.com/en_GB/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
				<img alt="" border="0" src="https://www.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
				</form>
			</div>
		</div>	
		<!-- 
		 "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
		 -->
			 <div id="five_job_payment">
		 		<h3>5 Job Listings</h3>
		 		<div class="paypalbutton2">
					<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
					<input type="hidden" name="cmd" value="_xclick">
					<input type="hidden" name="business" value="FF6Q6HD44S4R6">
					<input type="hidden" name="lc" value="GB">
					<input type="hidden" name="item_name" value="Five HotSeats Job Listings">
					<input type="hidden" name="item_number" value= "<%= @job.id %>">
					<input type="hidden" name="amount" value="496.00">
					<input type="hidden" name="currency_code" value="GBP">
					<input type="hidden" name="button_subtype" value="services">
					<input type="hidden" name="no_note" value="1">
					<input type="hidden" name="no_shipping" value="1">
					<input type="hidden" name="custom" value="5job">
					<input type="hidden" name="notify_url" value="<%= pn_url %>">
					<input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynow_LG.gif:NonHosted">
					<input type="image" src="https://www.paypal.com/en_GB/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">

					<img alt="" border="0" src="https://www.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
					</form>
				</div>
			</div>

		<% if current_employer %>
		<div id="prepaid">
			<h5>Your prepaid Job Balance is:
			<%= current_employer.prepaid  %>
			<% if current_employer.prepaid > 0 %>

			<%= link_to 'Pay with prepaid Balance', prepaid_path(@job.id) %></h5>
			<% end %>
		</div>	
		<% end %>		

	</div>
</div>

<%= render "layouts/footer" %>

app/views/jobs/prepaid.haml
= @message
= link_to "Return to the home page", root_path
= debug @job
= render "layouts/footer"

app/views/jobs/prepaid.html.erb
<%= @message %>

<%= link_to "Return to the home page", root_path %>

<%= debug @job %>

<%= render "layouts/footer" %>

app/views/jobs/show.haml
= render "layouts/header"
#wrapper.container_24
  #jobcontainer.grid_17
    #viewjob 
      %p
        #notice= notice
        
        %h1= @job.title
      %p
        
        = @job.employer.company_name
      %p  
        = image_tag @job.employer.logo
      %p  
        %b Location:
        = @job.location
      %p
        %b Position Type:
        = @job.position_type
      %p
        %b Job Description:
      %p 
        = raw sanitize(simple_format(@job.description), :tags => %w(br p) )
      %p
       
        %b Company Website:
        = @job.employer.website 
      %p
        %b How to Apply:
      %p.redlink
        -if current_applicant && current_applicant.approved == true 
          = raw sanitize(simple_format(@job.info), :tags => %w(br p) )
        -elsif current_applicant
          Your Job Seekers account is currently being reviewed by a member of the Hotseats Team
        -else
          You need to #{link_to 'Sign Up', new_applicant_registration_path } or #{link_to 'Log In', new_applicant_session_path } to apply for jobs  
      %p
      
        -if current_applicant && current_applicant.approved == true
          .redbutton_sidebar
            .buttontext=link_to "Apply", apply_path(@job) unless current_applicant.applied_to?(@job) 
        
  #sidebar.grid_7
    .sidebarheader
      %h3 100% Satisfaction Guarantee
    .sidebarline
    .sidebar_content
      %p
        Post your job on HotSeats.co and if you're
        not completely satisfied with the results
        you receive simply contact us for a full
        and courteous refund
    .sidebarheader
      %h3 "My CV was one of the best CVs the company had ever seen."
    
    .redlink
      %p
        Receive a full report on your CV's strengths and weaknesses #{link_to 'CLICK HERE', "http://www.careerconsultants.co.uk/find-me-a-job/cv-assessment/" }
    %h3 Post a Job
    .sidebarline
    .sidebar_content
      %p Post a job with HotSeats.co today for guaranteed recruitment satisfaction.
    .redbutton_sidebar
      .buttontext= link_to 'Post Job', new_jobs_path
  .clear
  =render "layouts/footer"