config/routes.rb
Hotseats::Application.routes.draw do
  
  resources :payment_notifications

  post 'payment_notifications', to: "payment_notifications#create", as: "pn"

  devise_for :applicants

  devise_for :employers
  get '/post-a-job', to: "jobs#new"
  get '/welcome', to: "info#welcome", as: "welcome"
  get '/apply-to-job/:id', to: "job_applications#create", as: "apply" 
  get 'view-job/:id', to: "jobs#show", as: "viewjob"
  get 'view-applications/:id', to: "jobs#applications", as: "viewapplications"
  get 'my-jobs', to: "jobs#myjobs", as: "myjobs"
  get 'approve-applicants', to: "admins#approve", as: "approveid"
  put 'approve-applicants/:id', to: "admins#update", as: "ap"
  get 'employer', to: "info#employer"
  get 'guarantee', to: "info#guarantee"
  get 'jobpayment', to: "jobs#payment"
  get 'prepaid/:id', to: "jobs#prepaid", as: "prepaid"

  mount Monologue::Engine, at: '/blog' 

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  resource :jobs
  
  root to: "info#home"
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def home

  	if params[:search]
  		params[:page] == 1
  		@jobpaid = Job.where(:jobpaid => "t")
    	@finder = @jobpaid.find(:all, :include => :employer, :conditions => ['title ILIKE ?', "%#{params[:search]}%"])
    	@jobs = Kaminari.paginate_array(@finder).page(params[:page]).per(10)

    else
    	   @jobs = Job.where(:jobpaid => true).order("created_at DESC").page(current_page).per(10)
    end

  end
  
end

app/helpers/info_helper.rb
module InfoHelper
	def dateformat(job)
		job.created_at.to_formatted_s(:long_ordinal)

	end
end	

app/views/info/contact.haml
= render "layouts/header"
#wrapper.container_24
  #jobcontainer.grid_17.sidebarline
    .title
      %h1 Contact Us
    .contactcontent
      %p
        HotSeats.co works with employers across the UK. We enjoy helping great companies
        connect with talented professionals. Give us a call or send us an email anytime - we
        are always happy to help and would love to hear from you.
      %p Call us:
      %h6 0161 212 2388
      %p Mailing Address:
      %h6
        St James Court‎
        30 Brown St, Manchester, Greater Manchester M2 1DH, UK
  #sidebar.grid_7
    .sidebarheader
      %h3 100% Satisfaction Guarantee
    .sidebarline
    .sidebar_content
      %p
        Post your job on HotSeats.co and if you're
        not completely satisfied with the results
        you receive simply contact us for a full
        and courteous refund
    .sidebarheader
      %h3 A few of the future customers of HotSeats
    .sidebarline
    %h3 Post a Job
    .sidebarline
    .sidebar_content
      %p Post a job with HotSeats.co today for guaranteed recruitment satisfaction.
    .redbutton_sidebar
      .buttontext= link_to "Post job", new_jobs_path
  .clear
  .space

app/views/info/contact.html.erb
<%= render "layouts/header" %>
<div id="wrapper" class="container_24">
	<div id="jobcontainer" class= "grid_17 sidebarline ">
		<div class="title">
		<h1>Contact Us</h1>
		</div>
		<div class="contactcontent">
				<p>HotSeats.co works with employers across the UK. We enjoy helping great companies 
				connect with talented professionals. Give us a call or send us an email anytime - we 
				are always happy to help and would love to hear from you.</p>

				<p>Call us: <h6>0161 212 2388</h6></p>

				<p>Mailing Address:<h6>St James Court‎
30 Brown St, Manchester, Greater Manchester M2 1DH, UK</h6></p> 
		</div>				
	</div>
	<div id="sidebar" class="grid_7">
		<div class="sidebarheader">
			<h3>100% Satisfaction Guarantee</h3>
		</div>
		<div class="sidebarline"></div>
		<div class="sidebar_content">	
			<p>Post your job on HotSeats.co and if you're
				not completely satisfied with the results
				you receive simply contact us for a full
				and courteous refund</p>
		</div>
		<div class="sidebarheader">
		<h3>A few of the future customers of HotSeats</h3>
		</div>
		<div class="sidebarline"></div>
		
		<h3>Post a Job</h3>
			<div class="sidebarline"></div>
		<div class="sidebar_content">	
			<p>Post a job with HotSeats.co today for guaranteed recruitment satisfaction.</p>
		</div>

		<div class="redbutton_sidebar">
			<div class="buttontext"><%= link_to "Post job", new_jobs_path %></div>
		</div>
	</div>
	
	<div class="clear"></div>
<div class="space"></div>

app/views/info/employer.haml
= render "layouts/header"
#wrapper.container_24
  #jobcontainer.grid_24
    .employerstitle
      %h1 The Easy and Proven Way to Reach Qualified Marketing, Communications and Creative Professionals in the UK
    .employersclients.grid_10.push_2
      = image_tag("clientsbig.png", :alt => "clients big")
    .employerscontent.grid_10.push_2
      %h2
        Why these companies and many
        more are turning to HotSeats.co
        to find and hire qualified talent...
      HotSeats.co is the leading jobsite specializing in marketing, communications and creative jobs in the UK. Since our start in 2010, hundreds of employers in a wide-range of industries have used HotSeats.co to save time and reach more candidates with the skills and experience they are looking for.
      %br/
      %br/
      Over 60,000 job seeking professionals visit our jobsite each month, and jobs are promoted through social media, our partner network, and in our member newsletter. Plus, every job posting comes with a 100% money-back guarantee if you are not satisfied for any reason.
    .clear
    .grid_9.redline.push_1
    .redbutton_employers.grid_4.push_1
      .buttontext_employer
        = image_tag("flamesmall.png", :alt => "HotSeats.co Logo", :class => "employer_fire_button")
        = link_to "Post Job", new_jobs_path
    .grid_9.redline.push_1
  .space
  = render "layouts/footer"

app/views/info/employer.html.erb
<%= render "layouts/header" %>
<div id="wrapper" class="container_24">
		<div id="jobcontainer" class= "grid_24">

				<div class="employerstitle">
				<h1> The Easy and Proven Way to Reach Qualified Marketing, Communications and Creative Professionals in the UK</h1>
				</div>

				<div class="employersclients grid_10 push_2">
				<%= image_tag("clientsbig.png", :alt => "clients big") %>
				</div>

				<div class="employerscontent grid_10 push_2">
					<h2>Why these companies and many
			more are turning to HotSeats.co
			to find and hire qualified talent...</h2>
			HotSeats.co is the leading jobsite specializing in marketing, communications and creative jobs in the UK. Since our start in 2010, hundreds of employers in a wide-range of industries have used HotSeats.co to save time and reach more candidates with the skills and experience they are looking for.
			<br />
			<br />
			Over 60,000 job seeking professionals visit our jobsite each month, and jobs are promoted through social media, our partner network, and in our member newsletter. Plus, every job posting comes with a 100% money-back guarantee if you are not satisfied for any reason.
			</div>
			<div class="clear"></div>
			<div class="grid_9 redline push_1"></div>

			<div class="redbutton_employers grid_4 push_1">
				<div class="buttontext_employer"><%= image_tag("flamesmall.png", :alt => "HotSeats.co Logo", :class => "employer_fire_button") %><%=link_to "Post Job", new_jobs_path %></div>
			</div>

			<div class="grid_9 redline push_1"></div>
				
		</div>
		
<div class="space"></div>

<%= render "layouts/footer" %>

app/views/info/guarantee.haml
= render "layouts/header"
#wrapper.container_24
  #jobcontainer.grid_24
    .guatitle
      %h1 100% Satisfaction Guaranteed. No Questions Asked.
    .grid_20.redline_gua.push_2
    .guacontent.grid_18.push_3
      %p
        Post your job on HotSeats.co and if you are not happy with the results you receive from your listing
        we will be happy to give you a prompt and courteous refund. No questions asked.
        %br/
        %br/
        Your satisfaction is extremely important to us and we want you to keep coming back to HotSeats.co.
        To request a refund simply contact us within 30 days of your job being posted and provide us with
        the details of your posting (your name, company, date of posting, etc).
      %p
    .clear
    .grid_9.redline.push_1
    .redbutton_employers.grid_4.push_1
      .buttontext= link_to "Post Job", new_jobs_path
    .grid_9.redline.push_1
  .space
= render "layouts/footer"

app/views/info/guarantee.html.erb
<%= render "layouts/header" %>
<div id="wrapper" class="container_24">
<div id="jobcontainer" class= "grid_24 ">

		<div class="guatitle">
		<h1>100% Satisfaction Guaranteed. No Questions Asked.</h1>
		</div>

		<div class="grid_20 redline_gua push_2"></div>
		<div class="guacontent grid_18 push_3">
			<p>Post your job on HotSeats.co and if you are not happy with the results you receive from your listing 
		we will be happy to give you a prompt and courteous refund. No questions asked.
		<br /><br />
		Your satisfaction is extremely important to us and we want you to keep coming back to HotSeats.co.
		To request a refund simply contact us within 30 days of your job being posted and provide us with 
		the details of your posting (your name, company, date of posting, etc).<p>
	</div>
	<div class="clear"></div>

	<div class="grid_9 redline push_1"></div>

	<div class="redbutton_employers grid_4 push_1">
		<div class="buttontext"><%= link_to "Post Job", new_jobs_path %></div>
	</div>

	<div class="grid_9 redline push_1"></div>
</div>
			
<div class="space"></div>

</div>
<%= render "layouts/footer" %>

app/views/info/home.haml
= render "layouts/header"
= render "layouts/navbar"
#wrapper.container_24/

#herobox
  #herotitle
    %h1
      Reach Qualified Marketing, Communications and
      Creative Professionals in the UK - Guaranteed.
  #herobuttons
    .greybutton
      .buttontext= link_to 'Learn more', employer_path
    #or or
    .redbutton
      .buttontext= link_to 'Post Job Now', new_jobs_path
  .piclist
    %ol
      %li Access a qualified applicant pool more quickly
      %li Get the results you want or your money back
#jobcontainer.grid_17
  #search
    #searchbar
      = form_tag "", :method => 'get' do
        = text_field_tag :search, params[:search]
        = submit_tag "Search", :name => nil

  #joblist
    - @jobs.each do |job|
      %div{:class => cycle('listing', 'listing_white')}
        .job_title
          = link_to job.title, viewjob_path(job)
          
        .location
          = job.location
        .clear
        .at_symbol
          @
        .employer_title
          = job.employer.company_name
          / = link_to job.title, jobs_path(job)

        .date_stamp

          = dateformat job
  #pagination
    =paginate @jobs  
     
  #scoop
    .scoopline
      %h3 The Scoop on HotSeats.co
    .scooppara
      HotSeats.co is the UK's #1 jobsite specializing in marketing, communication and creative jobs. UK's top employers and brands to small business from across the country post their jobs on HotSeats.co to find qualified marketing, communications and creative professionals.
      %br/
      %br/
      Whether you are looking for a professional in Marketing, Public Relations, Social Media, Branding, Design, SEO/SEM, Communications or Copywriting - HotSeats.co is the place to find them.
      %br/
      %br/
      Posting your job on HotSeats.co is easy, affordable and comes with a 100% satisfaction guarantee. Your job will also be seen by hundreds of thousands of passive candidates on HotSeats.co partner websites, giving you unprecedented exposure to ensure you find the most qualified candidates.
      %r
        = link_to 'Post Your Job Now', new_jobs_path

#sidebar.grid_7
  .sidebarheader
  %h3 "My CV was one of the best CVs the company had ever seen."
.sidebarline.grid_7
.sidebar_content.grid_7
  .redlink
    %p
      Receive a full report on your CV's strengths and weaknesses #{link_to 'CLICK HERE', "http://www.careerconsultants.co.uk/find-me-a-job/cv-assessment/" }
.sidebar_content.grid_7
  %h3 Post a Job
  .sidebarline
.sidebar_content.grid_7
  %p Post a job with HotSeats.co today for guaranteed recruitment satisfaction.
.redbutton_sidebar
  .buttontext= link_to 'Post Job', new_jobs_path
.clear     

= render "layouts/footer"        

app/views/info/welcome.haml
%h2 An email has been sent to your email address to confirm your account. 

%strong
  =flash[:notice]
  
  