config/routes.rb
Hotseats::Application.routes.draw do
  
  resources :payment_notifications

  post 'payment_notifications', to: "payment_notifications#create", as: "pn"

  devise_for :applicants

  devise_for :employers
  get '/post-a-job', to: "jobs#new"
  get '/welcome', to: "info#welcome", as: "welcome"
  get '/apply-to-job/:id', to: "job_applications#create", as: "apply" 
  get 'view-job/:id', to: "jobs#show", as: "viewjob"
  get 'view-applications/:id', to: "jobs#applications", as: "viewapplications"
  get 'my-jobs', to: "jobs#myjobs", as: "myjobs"
  get 'approve-applicants', to: "admins#approve", as: "approveid"
  put 'approve-applicants/:id', to: "admins#update", as: "ap"
  get 'employer', to: "info#employer"
  get 'guarantee', to: "info#guarantee"
  get 'jobpayment', to: "jobs#payment"
  get 'prepaid/:id', to: "jobs#prepaid", as: "prepaid"

  mount Monologue::Engine, at: '/blog' 

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  resource :jobs
  
  root to: "info#home"
end

app/views/layouts/_footer.haml
-#sidebar.grid_7
  .sidebarheader
    %h3 A few of the future customers of HotSeats
  .sidebarline
  %h3 Post a Job
  .sidebarline
  .sidebar_content
    %p Post a job with HotSeats.co today for guaranteed recruitment satisfaction.
  .redbutton_sidebar
    .buttontext= link_to 'Post Job'
.clear


#footer.container_24
  %ol
    %li= link_to "Jobs", root_path

  .vertline
  %ol
    %li Job Seekers
    %li= link_to "Sign Up", new_applicant_registration_path
    %li= link_to "Login", new_applicant_session_path 
    %li
  .vertline
  %ol
    %li Employers
    %li= link_to "Login", new_employer_session_path 
    %li= link_to "Guarantee", guarantee_path
   
  .vertline
  %ol
    %li About
    %li= link_to "Contact", contact_path
  .vertline
  / %ol
  /   %a{:href => "/blog"} Blog
    
.space

app/views/layouts/_header.haml
#header
  #headercontent.container_24
    #flash
      = flash[:notice]
    #logo
      = link_to image_tag("logo.png", :alt => "HotSeats.co Logo"), root_path
    #social
      - if current_employer
        Employers:
        \#{link_to "My Jobs", myjobs_path}
        \#{link_to "Logout", destroy_employer_session_path, :method=>:delete}
      - else
      - unless current_employer
        - if current_applicant
          = link_to "Logout", destroy_applicant_session_path, :method=>:delete
        - else
          Job Seekers:
          \#{link_to "Login", new_applicant_session_path}
          \#{link_to "Signup", new_applicant_registration_path}
      = link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com'
      = link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com'
      = link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/'
    .clear
    %div{:style => "background: Red; width: 200px;"}
    #navbar
      %ol
        %li
          = link_to "Jobs", root_path
        %li
          = link_to "Post Job", new_jobs_path
        %li
          = link_to "Employers", employer_path
        %li
          = link_to "Guarantee", guarantee_path
        %li
          %a{:href => "/blog"} Blog
        %li
          = link_to "Contact", contact_path
        %li
          = link_to "Employer Login", new_employer_session_path

app/views/layouts/_header.html.erb
<div id="header">
	<div id="headercontent" class="container_24">
		<div id= "flash"><%= flash[:notice] %> </div>
		<div id="logo">
			<%= link_to image_tag("logo.png", :alt => "HotSeats.co Logo"), root_path  %>
		</div>
		<div id="social">
			
			<%- if current_employer %>
			Employers:
			<%= link_to "My Jobs", myjobs_path %>
			<%= link_to "Logout", destroy_employer_session_path, :method=>:delete %>
		<%- else %>
			
		<%- end%>

		<%- unless current_employer %>
			<%- if current_applicant %>
			
				<%= link_to "Logout", destroy_applicant_session_path, :method=>:delete %>
			<%- else %>
			Job Seekers:
				<%= link_to "Login", new_applicant_session_path  %>
				<%= link_to "Signup", new_applicant_registration_path  %>
		
			<%- end%>
			
		<%-end%>

		<%= link_to image_tag("facebook.png", :alt => "facebook small logo"), 'http://www.facebook.com' %>
		<%= link_to image_tag("twitter.png", :alt => "facebook small logo"), 'http://www.twitter.com' %>
		<%= link_to image_tag("google-plus.png", :alt => "facebook small logo"), 'http://plus.google.com/' %>
			
		</div>

		<div class="clear"></div>
		<div style="background: Red; width: 200px;">
		</div>

		<div id="navbar" class="">
			<ol>
				<li>
					<%= link_to "Jobs", root_path %>
				</li>
				<li>
					<%= link_to "Post Job", new_jobs_path %>
				</li>
				<li>
					<%= link_to "Employers", employer_path %>
				</li>
				<li>
					<%= link_to "Guarantee", guarantee_path %>
				</li>

				<li>
					<a href="/blog">Blog</a>
				<li>
					<%= link_to "Contact", contact_path %>
				</li>
				<li> <%= link_to "Employer Login", new_employer_session_path  %> </li>
			</ol>
		</div>
	</div>
</div>

app/views/layouts/application.haml
!!!
%html
  %head
    %title Hotseatsco
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield
    = debug(params) if Rails.env.development?

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Hotseatsco</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		  
	
		<%= yield %>
		
		<%= debug(params) if Rails.env.development? %>

	</body>
</html>